"""maj des models

Revision ID: 543e06cdbe7e
Revises: 85d0a965809a
Create Date: 2024-04-02 11:10:25.283036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543e06cdbe7e'
down_revision = '85d0a965809a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
