"""maj

Revision ID: 6065c32ca0ee
Revises: 1789590bc51e
Create Date: 2024-05-03 13:54:10.734544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6065c32ca0ee'
down_revision = '1789590bc51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notifications')
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_requiring_improvement', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('affected_population', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('concerns_of_affected_population', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('impact_on_affected_population', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quantitative_volume_affected_population', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('quantitative_volume_affected_population')
        batch_op.drop_column('impact_on_affected_population')
        batch_op.drop_column('concerns_of_affected_population')
        batch_op.drop_column('affected_population')
        batch_op.drop_column('activity_requiring_improvement')

    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Notifications')
    # ### end Alembic commands ###
