"""maj des models

Revision ID: a91529df1736
Revises: 7de40e210baf
Create Date: 2024-03-30 23:58:28.635546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91529df1736'
down_revision = '7de40e210baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cover', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('social_link', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('activity_domain', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('group', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('work_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('language')
        batch_op.drop_column('website')
        batch_op.drop_column('work_title')
        batch_op.drop_column('group')
        batch_op.drop_column('notifications')
        batch_op.drop_column('activity_domain')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('password')
        batch_op.drop_column('social_link')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')
        batch_op.drop_column('cover')
        batch_op.drop_column('full_name')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
