"""maj des models

Revision ID: c6b8e6ed2dc1
Revises: 543e06cdbe7e
Create Date: 2024-04-02 12:13:29.069091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b8e6ed2dc1'
down_revision = '543e06cdbe7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth')
    op.drop_table('passwords')
    op.drop_table('journalisations')
    op.drop_table('Invitations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Invitations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Invitations_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Invitations_pkey')
    )
    op.create_table('journalisations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='journalisations_pkey')
    )
    op.create_table('passwords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='passwords_pkey')
    )
    op.create_table('auth',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_pkey')
    )
    # ### end Alembic commands ###
